# Generated by Django 3.0.6 on 2020-06-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='choice',
            field=models.CharField(blank=True, choices=[('F', 'Full Time'), ('P', 'Part Time'), ('I', 'Internship')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='listapp.Req'),
        ),
    ]
