# Generated by Django 3.0.6 on 2020-06-02 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0003_auto_20200602_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Jobtype',
            new_name='jobtype',
        ),
    ]
