# Generated by Django 3.0.6 on 2020-06-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0004_auto_20200602_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='now',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Req',
        ),
    ]
