# Generated by Django 3.0.6 on 2020-06-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0005_auto_20200611_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='now',
        ),
    ]
