# Generated by Django 3.0.6 on 2020-06-12 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0006_remove_job_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 17, 2, 51, 285199)),
        ),
    ]
