# Generated by Django 3.0.6 on 2020-06-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0007_auto_20200612_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted',
            field=models.DateTimeField(),
        ),
    ]
