# Generated by Django 3.0.3 on 2020-06-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20200529_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='creditCards',
        ),
        migrations.DeleteModel(
            name='shippingAddress',
        ),
    ]
