# Generated by Django 3.0.7 on 2020-07-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='applicationinfo',
            name='Address',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='Address',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='users',
            name='Address',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
