# Generated by Django 3.0.7 on 2020-07-31 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200731_1617'),
    ]

    operations = [
        
    ]
