# Generated by Django 3.0.6 on 2020-07-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200603_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='educationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('duration', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=40)),
                ('major', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('Address', models.CharField(blank=True, max_length=40)),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
                ('nickName', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(default='default.png', upload_to='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='workExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=40)),
                ('years', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=150)),
                ('Username', models.CharField(max_length=20)),
            ],
        ),
    ]
