# Generated by Django 3.0.6 on 2020-07-08 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_educationexperience_users_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Company Name')),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=40, verbose_name='Address')),
                ('company_description', models.CharField(blank=True, max_length=500, verbose_name="Company's Description")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
