# Generated by Django 3.0.6 on 2020-07-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='banner',
            field=models.ImageField(default='boeing_logo.jpg', upload_to='company_logos'),
        ),
    ]
