# Generated by Django 3.0.6 on 2020-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_companyprofile_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jobtype', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('RJ', 'Rejected'), ('PR', 'Pending')], default='PR', max_length=2)),
            ],
        ),
    ]
