# Generated by Django 3.0.6 on 2020-07-15 23:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jobform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('postdate', models.DateField()),
                ('posttime', models.TimeField()),
                ('deadlinedate', models.DateField()),
                ('deadlinetime', models.TimeField()),
                ('zipcode', models.CharField(default='00000', max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postjob.Jobtype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
