# Generated by Django 3.0.7 on 2020-06-25 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobform',
            name='zipcode',
            field=models.CharField(default='00000', max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
