# Generated by Django 3.0.7 on 2020-07-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobform',
            name='company',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
