# Generated by Django 3.0.6 on 2020-05-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('First_Name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='First Name')),
                ('Middle_Name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Middle Name')),
                ('Last_Name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Last Name')),
            ],
        ),
    ]
